name: Add locale

on:
  workflow_dispatch:

concurrency:
  group: "update-locale"
  cancel-in-progress: false

jobs:
  create-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine next year
        id: get-next-year
        run: |
          CURRENT_YEAR=$(date +'%Y')
          echo "year=$(( CURRENT_YEAR ))" >> "${GITHUB_OUTPUT}"

      - name: Set up Python environment
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install holidata

      - name: Add data for the next year
        run: |
          year="${{ steps.get-next-year.outputs.year }}"
          formats=( "json" "yaml" "xml" "csv" )
          
          for locale_dir in holidata/??-?? ; do
            locale="${locale_dir/holidata\//}"
            echo "Generating locale '${locale}' files for ${year}..."
            for format in "${formats[@]}" ; do
              echo "Generating ${locale}/${year}.${format}"
              venv/bin/holidata --year="${year}" --locale="${locale}" --output="${format}" > "${locale_dir}/${year}.${format}"
            done
          
            echo "Generated locale ${locale} for year ${year}"
          done
        continue-on-error: false

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          author: "Holidata Bot <holidata-bot@users.noreply.github.com>"
          title: Updated locales for year ${{ steps.get-next-year.outputs.year }}
          body: |
            Updated locales for year ${{ steps.get-next-year.outputs.year }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: add-${{ github.event.inputs.locale }}

#      - name: Merge Pull Request
#        if: "${{ steps.cpr.outputs.pull-request-number != '' }}"
#        uses: juliangruber/merge-pull-request-action@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          number: ${{ steps.cpr.outputs.pull-request-number }}
#          method: rebase
