name: Add locale

on:
  workflow_dispatch:
    inputs:
      locale:
        description: "Locale in format [a-z]{2}-[A-Z]{2}"
        required: true

concurrency:
  group: "update-locale"
  cancel-in-progress: false

jobs:
  create-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check locale format
        run: |
          if! echo "$LOCALE" | grep -qE "^[a-z]{2}-[A-Z]{2}$"; then
            echo "Error: Locale '$LOCALE' does not match the required format [a-z]{2}-[A-Z]{2}"
            exit 1
          fi
        env:
          LOCALE: ${{ github.event.inputs.locale }}

      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install holidata

      - name: Run Python script
        run: |
          python create_locale_data.py ${{ github.event.inputs.locale }}
        continue-on-error: false

#      - name: Create Pull Request
#        id: cpr
#        uses: peter-evans/create-pull-request@v6
#        with:
#          delete-branch: true
#          commit-message: Updated tools-data.json
#          author: "Timewarrior Tools Bot <timew-tools-bot@users.noreply.github.com>"
#          title: Updated tools-data.json
#          body: |
#            - Updated `tools-data.json`
#
#            Auto-generated by [create-pull-request][1]
#
#            [1]: https://github.com/peter-evans/create-pull-request
#          branch: add-${{ github.event.inputs.locale }}
#
#      - name: Merge Pull Request
#        if: "${{ steps.cpr.outputs.pull-request-number != '' }}"
#        uses: juliangruber/merge-pull-request-action@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          number: ${{ steps.cpr.outputs.pull-request-number }}
#          method: rebase
