name: Upgrade year

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 8 *'

concurrency:
  group: "update-locales"
  cancel-in-progress: false

jobs:
  upgrade-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine next year
        id: get-next-year
        run: |
          CURRENT_YEAR=$(date +'%Y')
          echo "year=$(( CURRENT_YEAR + 1 ))" >> "${GITHUB_OUTPUT}"

      - name: Set up Python environment
        run: |
          python -m venv /tmp/venv
          /tmp/venv/bin/pip install --upgrade pip
          /tmp/venv/bin/pip install holidata

      - name: Upgrade locales years
        id: upgrade-year
        run: |
          YEAR="${{ steps.get-next-year.outputs.year }}"
          FORMATS=( "json" "yaml" "xml" "csv" )
          
          for locale_dir in holidata/??-?? ; do
            LOCALE="${locale_dir/holidata\//}"
            echo "Generating locale '${locale}' files for ${YEAR}..."

            for format in "${FORMATS[@]}" ; do
              echo "Generating ${LOCALE}/${YEAR}.${format}"
              /tmp/venv/bin/holidata --year="${YEAR}" --locale="${LOCALE}" --output="${format}" > "${locale_dir}/${YEAR}.${format}"
            done
          
            echo "Generated locale ${LOCALE} for year ${YEAR}"
            echo "${LOCALE##*-}" >> /tmp/countries
          done

          sort -u < /tmp/countries > /tmp/sorted
          COUNTRIES="$( paste -s -d, /tmp/sorted )"
          echo "countries=${COUNTRIES//,/, }" >> "${GITHUB_OUTPUT}"
        continue-on-error: false

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          commit-message: |
            Updated locales of ${{ steps.upgrade-year.outputs.countries }} for year ${{ steps.get-next-year.outputs.year }}
          author: "Holidata Bot <holidata-bot@users.noreply.github.com>"
          title: Updated locales for year ${{ steps.get-next-year.outputs.year }}
          body: |
            Updated locales of ${{ steps.upgrade-year.outputs.countries }} for year ${{ steps.get-next-year.outputs.year }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: upgrade-year

#      - name: Merge Pull Request
#        if: "${{ steps.cpr.outputs.pull-request-number != '' }}"
#        uses: juliangruber/merge-pull-request-action@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          number: ${{ steps.cpr.outputs.pull-request-number }}
#          method: rebase
