name: Upgrade year

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 8 *'

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  upgrade-year:
    runs-on: ubuntu-latest
    concurrency:
      group: "update-locales"
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine next year
        id: get-next-year
        run: |
          CURRENT_YEAR=$(date +'%Y')
          echo "year=$(( CURRENT_YEAR ))" >> "${GITHUB_OUTPUT}"

      - name: Set up Python environment
        run: |
          python -m venv /tmp/venv
          /tmp/venv/bin/pip install --upgrade pip
          /tmp/venv/bin/pip install holidata

      - name: Upgrade locales years
        id: upgrade-year
        run: |
          YEAR="${{ steps.get-next-year.outputs.year }}"
          FORMATS=( "json" "yaml" "xml" "csv" )
          
          for locale_dir in holidata/??-?? ; do
            LOCALE="${locale_dir/holidata\//}"
            echo "Generating locale '${locale}' files for ${YEAR}..."

            for format in "${FORMATS[@]}" ; do
              echo "Generating ${LOCALE}/${YEAR}.${format}"
              /tmp/venv/bin/holidata --year="${YEAR}" --locale="${LOCALE}" --output="${format}" > "${locale_dir}/${YEAR}.${format}"
            done
          
            echo "Generated locale ${LOCALE} for year ${YEAR}"
            echo "${LOCALE##*-}" >> /tmp/countries
          done

          sort -u < /tmp/countries > /tmp/sorted
          COUNTRIES="$( paste -s -d, /tmp/sorted )"
          echo "countries=${COUNTRIES//,/, }" >> "${GITHUB_OUTPUT}"
        continue-on-error: false

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          commit-message: |
            Updated locales of ${{ steps.upgrade-year.outputs.countries }} for year ${{ steps.get-next-year.outputs.year }}
          author: "Holidata Bot <holidata-bot@users.noreply.github.com>"
          title: Updated locales for year ${{ steps.get-next-year.outputs.year }}
          body: |
            Updated locales of ${{ steps.upgrade-year.outputs.countries }} for year ${{ steps.get-next-year.outputs.year }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: upgrade-year

      - name: Merge Pull Request
        if: "${{ steps.cpr.outputs.pull-request-number != '' }}"
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: rebase

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: upgrade-year
    concurrency:
      group: "pages"
      cancel-in-progress: false
    env:
      HUGO_VERSION: 0.124.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
